[package]
name = "facto-loop-miner"
version = "0.1.0"
edition = "2021"

default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.0"
jemallocator = "0.5.4"
num-format = "0.4.4"
num-traits = "0.2.16"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = { version = "1.0.104" }
simd-json = { version = "0.13.9", features = ["serde"] }
opencv = { version = "0.89.0", default-features = false, features = [
    "clang-runtime",
    "imgcodecs",
    "imgproc"
] }

strum = { version = "0.26.2", features = ["derive"] }
itertools = "0.12.1"
kiddo = "4.2.0"
pathfinding = { version = "4.9.1", path = "../../pathfinding" }
rayon = "1.7.0"
bitvec = "1.0.1"
lazy_static = "1.4.0"
mimalloc = "0.1.39"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tracing-test = "0.2.4"
rcon-client = "0.1.2"
thiserror = "1.0.50"
regex = "1.10.2"
crossbeam = "0.8.2"
clap = { version = "4.4.11", features = ["derive"] }
bytemuck = { version = "1.14.0", features = ["extern_crate_alloc"] }
enum-map = "2.7.3"
facto-loop-miner-io = { path = "../io_experiments" }
rand = "0.8.5"
