[package]
name = "facto-loop-miner-fac-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13.0"
num-format = "0.4.4"
rand = "0.8.5"
regex = "1.11.1"
strum = "0.26.3"
strum_macros = "0.26.3"
thiserror = "2.0.3"
tracing = "0.1.41"
rcon-client = "0.1.2"
serde = "1.0.215"
facto-loop-miner-common = { path = "../common" }