[package]
name = "facto-loop-miner-io"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.151"
memmap2 = "0.9.2"
thiserror = "1.0.50"
itertools = "0.12.0"
num-format = "0.4.4"
uring-sys2 = "0.8.0"